/*
 * ELEC5566 MINI-PROJECT:
 * SCORE DISPLAY
 * ---------------------------------
 * For: University of Leeds
 * Date: 19/5/2021
 *
 * Description
 * ---------------------------------
 * This module takes the score count
 * generated by the pipes module, converts
 * it to BCD, for display on both the 7segs
 * and the screen.
 *
 */

module score_display
(
	// INPUTS
	input rst,
	input	[31:0] score_count,
	
	// OUTPUTS
	output [11:0] score_BCD, hiscore_BCD,
	output [41:0] seven_seg
);

// Reg to store hiscore in current game session
// TODO: write/read from SD card or DDR3
reg [31:0] hiscore;

always @(score_count or rst)
begin
	if (rst)
		hiscore = 0;
	else
		hiscore = (score_count > hiscore) ? score_count : hiscore;
end

// Instantiate modules to convert binary score_count and hiscore to BCD
bin_to_BCD scr (score_count, score_BCD);
bin_to_BCD hiscr (hiscore, hiscore_BCD);

// Generate hex_to_7seg modules to convert each unit of the score_BCD
genvar i;
generate
	for (i = 0; i < 6; i = i + 1) begin : seven_seg_loop
		hex_to_7seg display
		(
			.hex		( i < 3 ? score_BCD[(i*4)+:4] : 0 	),
			.seven_seg	( seven_seg[(i*7)+:7] 			)
		);
	end 
endgenerate

endmodule
